// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzR6tisM8-oU-UeDcg76HsMQb8Omj-UXY',
    appId: '1:387404482815:web:5a222827f5bc0826c664ca',
    messagingSenderId: '387404482815',
    projectId: 'saidai-roomfinder',
    authDomain: 'saidai-roomfinder.firebaseapp.com',
    storageBucket: 'saidai-roomfinder.firebasestorage.app',
    measurementId: 'G-NBHLNZZ2Q2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05WUg3AWcJJyAzPVM4EQ84HJd0ke7LAY',
    appId: '1:387404482815:android:8cece073e4cf36edc664ca',
    messagingSenderId: '387404482815',
    projectId: 'saidai-roomfinder',
    storageBucket: 'saidai-roomfinder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxS2oY1t-Y98buoo9sOD6QxffliUbRYCc',
    appId: '1:387404482815:ios:3d760d36d0a8b878c664ca',
    messagingSenderId: '387404482815',
    projectId: 'saidai-roomfinder',
    storageBucket: 'saidai-roomfinder.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxS2oY1t-Y98buoo9sOD6QxffliUbRYCc',
    appId: '1:387404482815:ios:3d760d36d0a8b878c664ca',
    messagingSenderId: '387404482815',
    projectId: 'saidai-roomfinder',
    storageBucket: 'saidai-roomfinder.firebasestorage.app',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzR6tisM8-oU-UeDcg76HsMQb8Omj-UXY',
    appId: '1:387404482815:web:3f8037c8a15fee13c664ca',
    messagingSenderId: '387404482815',
    projectId: 'saidai-roomfinder',
    authDomain: 'saidai-roomfinder.firebaseapp.com',
    storageBucket: 'saidai-roomfinder.firebasestorage.app',
    measurementId: 'G-QS39M9E6GX',
  );
}
